replicaCount: 1

podAnnotations:
  linkerd.io/inject: enabled

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-production

jaeger:
  collector_host: dns:///jaeger-production-collector-headless.observability:14250

image:
  repository: registry.happytravel.com/komoro
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  grpc:
    port: 5101
  metrics:
    port: 60001
  healthchecks:
    port: 60000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
  hosts:
    - host: komoro.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: happytravel-tls
     hosts:
       - komoro.happytravel.com

resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 25m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: false
  podMonitor:
    enabled: false

env:
  ASPNETCORE_URLS: http://*:80
  ASPNETCORE_ENVIRONMENT: "Production"
  HTDC_VAULT_ENDPOINT: "https://vault.happytravel.com/v1/"
  HTDC_KOMORO_SENTRY_ENDPOINT: "https://b419fd24d56a4b7e85a117c3864a697a@sentry.happytravel.com/62"
  HTDC_REDIS_HOST: "redis-komoro"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  HTDC_WEBAPI_PORT: "80"
  HTDC_GRPC_PORT: "5101"
  HTDC_HEALTH_PORT: "60000"
  HTDC_METRICS_PORT: "60001"
  CONSUL_HTTP_ADDR: "https://consul.happytravel.com/"
